import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { InventoryItem, Stats, PredictionsResponse, ConsumptionHistoryEntry } from '../services/api';
import { getDaysToExpiry, isExpired, isExpiredOrExpiringSoon, formatExpiryLabel } from './expiry';
import { getSuggestedReorderQuantity } from './reorder';
import { getDaysLeft, getStockStatus } from './stock';
// CO2 factors and the "wasted" definition are shared with the sustainability
// widgets so the report can't quietly disagree with what's on screen.
import { getCO2Factor, isWasted } from './sustainability';

/**
 * Builds and downloads the "HappyShelf Inventory Report" PDF from data
 * already loaded on the Dashboard (items/stats/predictions) — no separate
 * backend call, so the report always reflects exactly what the user sees
 * on screen.
 */

interface GenerateReportParams {
  items: InventoryItem[];
  stats: Stats | null;
  predictions: PredictionsResponse | null;
  consumptionHistory?: ConsumptionHistoryEntry[];
  userName?: string;
}

type PdfWithAutoTable = jsPDF & { lastAutoTable?: { finalY: number } };

// Tailwind palette used elsewhere in the app, kept in sync so the report
// reads as an extension of the UI rather than a separately-designed document.
const GREEN_600: [number, number, number] = [22, 163, 74];
const GREEN_700: [number, number, number] = [21, 128, 61];
const GREEN_50: [number, number, number] = [240, 253, 244];
const GRAY_800: [number, number, number] = [31, 41, 55];
const GRAY_600: [number, number, number] = [75, 85, 99];
const GRAY_400: [number, number, number] = [156, 163, 175];
const WHITE: [number, number, number] = [255, 255, 255];

const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const MARGIN = 14;
const CONTENT_TOP = 26;
const CONTENT_BOTTOM = 20;

const getItemStatus = (item: InventoryItem): 'Out of Stock' | 'Expiring Soon' | 'Low Stock' | 'Healthy' => {
  const stock = getStockStatus(item);
  if (stock === 'out') return 'Out of Stock';
  if (isExpiredOrExpiringSoon(item.expiry_date, 7)) return 'Expiring Soon';
  if (stock === 'low') return 'Low Stock';
  return 'Healthy';
};

const generateReportId = (): string => {
  const datePart = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  const randomPart = Math.random().toString(36).slice(2, 8).toUpperCase();
  return `HS-${datePart}-${randomPart}`;
};

const formatCurrency = (value: number): string =>
  `Rs. ${value.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`;

const formatDate = (value: string | null | undefined): string => {
  if (!value) return 'N/A';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return 'N/A';
  return d.toLocaleDateString();
};

/** Green leaf glyph drawn as vector paths, echoing the lucide Leaf icon used in the app header. */
const drawLeafLogo = (doc: jsPDF, cx: number, cy: number, s: number, leafColor: [number, number, number]) => {
  const w = s * 0.62;
  doc.setFillColor(...leafColor);
  doc.lines(
    [
      [w, -0.6 * s, w, -1.4 * s, 0, -2 * s],
      [-w, 0.6 * s, -w, 1.4 * s, 0, 2 * s],
    ],
    cx,
    cy + s,
    [1, 1],
    'F',
    true
  );
  doc.setDrawColor(...WHITE);
  doc.setLineWidth(s * 0.08);
  doc.line(cx, cy + s * 0.75, cx, cy - s * 0.65);
};

const addBrandedHeader = (doc: jsPDF, reportId: string, generatedBy: string) => {
  doc.setFillColor(...GREEN_600);
  doc.rect(0, 0, PAGE_WIDTH, 32, 'F');

  doc.setFillColor(...WHITE);
  doc.roundedRect(MARGIN, 7, 18, 18, 4, 4, 'F');
  drawLeafLogo(doc, MARGIN + 9, 16, 5.5, GREEN_600);

  doc.setTextColor(...WHITE);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('HappyShelf', MARGIN + 24, 15);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.text('Smart Household Inventory Management System', MARGIN + 24, 21.5);

  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Inventory Report', PAGE_WIDTH - MARGIN, 15, { align: 'right' });

  // Meta strip below the brand band
  const now = new Date();
  doc.setFillColor(...GREEN_50);
  doc.rect(0, 32, PAGE_WIDTH, 16, 'F');
  doc.setTextColor(...GRAY_800);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.text(`Generated By: ${generatedBy}`, MARGIN, 39);
  doc.text(`Generated: ${now.toLocaleDateString()} ${now.toLocaleTimeString()}`, MARGIN, 44.5);
  doc.text(`Report ID: ${reportId}`, PAGE_WIDTH - MARGIN, 39, { align: 'right' });

  return 56;
};

const addSlimHeader = (doc: jsPDF) => {
  doc.setFillColor(...GREEN_600);
  doc.rect(0, 0, PAGE_WIDTH, 12, 'F');
  doc.setTextColor(...WHITE);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('HappyShelf', MARGIN, 8);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.text('Inventory Report', PAGE_WIDTH - MARGIN, 8, { align: 'right' });
};

const addFootersToAllPages = (doc: jsPDF) => {
  const totalPages = doc.getNumberOfPages();
  const now = new Date();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    if (i > 1) addSlimHeader(doc);

    doc.setDrawColor(...GRAY_400);
    doc.setLineWidth(0.2);
    doc.line(MARGIN, PAGE_HEIGHT - 15, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 15);

    doc.setTextColor(...GRAY_600);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text('Generated by HappyShelf', MARGIN, PAGE_HEIGHT - 10);
    doc.text(`${now.toLocaleDateString()} ${now.toLocaleTimeString()}`, PAGE_WIDTH / 2, PAGE_HEIGHT - 10, {
      align: 'center',
    });
    doc.text(`Page ${i} of ${totalPages}`, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 10, { align: 'right' });
  }
};

interface SectionCursor {
  y: number;
}

const ensureSpace = (doc: jsPDF, cursor: SectionCursor, needed: number) => {
  if (cursor.y + needed > PAGE_HEIGHT - CONTENT_BOTTOM) {
    doc.addPage();
    cursor.y = CONTENT_TOP;
  }
};

const addSectionTitle = (doc: jsPDF, cursor: SectionCursor, title: string) => {
  // Reserve room for the heading *plus* the start of whatever follows it, so a
  // title never ends up stranded alone at the bottom of a page with its table
  // beginning on the next one.
  ensureSpace(doc, cursor, 34);
  doc.setTextColor(...GREEN_700);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(title, MARGIN, cursor.y);
  doc.setDrawColor(...GREEN_600);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, cursor.y + 2, PAGE_WIDTH - MARGIN, cursor.y + 2);
  cursor.y += 8;
};

const addEmptyNotice = (doc: jsPDF, cursor: SectionCursor, message: string) => {
  ensureSpace(doc, cursor, 10);
  doc.setTextColor(...GRAY_600);
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9.5);
  doc.text(message, MARGIN, cursor.y);
  cursor.y += 10;
};

const addTable = (
  doc: jsPDF,
  cursor: SectionCursor,
  head: string[][],
  body: (string | number)[][],
  columnStyles?: Record<number, { cellWidth?: number; halign?: 'left' | 'center' | 'right' }>
) => {
  autoTable(doc, {
    head,
    body,
    startY: cursor.y,
    margin: { left: MARGIN, right: MARGIN, top: CONTENT_TOP, bottom: CONTENT_BOTTOM },
    theme: 'striped',
    styles: { fontSize: 8.5, cellPadding: 2.5, textColor: GRAY_800 },
    headStyles: { fillColor: GREEN_600, textColor: WHITE, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: GREEN_50 },
    columnStyles,
  });
  cursor.y = (doc as PdfWithAutoTable).lastAutoTable?.finalY ?? cursor.y;
  cursor.y += 10;
};

export const generateInventoryReportPdf = ({
  items,
  stats,
  predictions,
  consumptionHistory = [],
  userName,
}: GenerateReportParams): void => {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const reportId = generateReportId();
  const generatedBy = userName?.trim() || 'HappyShelf User';

  const startY = addBrandedHeader(doc, reportId, generatedBy);
  const cursor: SectionCursor = { y: startY };

  const itemsWithCost = items.filter((i) => i.cost_per_unit != null);
  const totalValue = items.reduce((sum, i) => sum + (i.quantity || 0) * (i.cost_per_unit || 0), 0);
  const categories = Array.from(new Set(items.map((i) => i.category)));
  const outOfStockItems = items.filter((i) => (i.quantity ?? 0) <= 0);
  const lowStockItems = stats?.lowStockItems ?? 0;
  const expiringSoonItems = items.filter((i) => isExpiredOrExpiringSoon(i.expiry_date, 7));
  const avgDailyUsage = items.length > 0 ? items.reduce((sum, i) => sum + (i.daily_usage || 0), 0) / items.length : 0;

  // ---------- 1. Inventory Summary ----------
  addSectionTitle(doc, cursor, '1. Inventory Summary');
  addTable(
    doc,
    cursor,
    [['Metric', 'Value']],
    [
      ['Total Items', String(items.length)],
      ['Total Categories', String(categories.length)],
      ['Total Inventory Value', formatCurrency(totalValue)],
      ['Low Stock Items', String(lowStockItems)],
      ['Out of Stock Items', String(outOfStockItems.length)],
      ['Items Expiring in 7 Days', String(expiringSoonItems.length)],
      ['Average Daily Usage', `${avgDailyUsage.toFixed(2)} units/day`],
    ],
    { 0: { cellWidth: 80 } }
  );

  // ---------- 2. Category Summary ----------
  addSectionTitle(doc, cursor, '2. Category Summary');
  if (categories.length === 0) {
    addEmptyNotice(doc, cursor, 'No categories to display.');
  } else {
    const categoryMap = new Map<string, { count: number; qty: number; value: number }>();
    items.forEach((item) => {
      const entry = categoryMap.get(item.category) || { count: 0, qty: 0, value: 0 };
      entry.count += 1;
      entry.qty += item.quantity || 0;
      entry.value += (item.quantity || 0) * (item.cost_per_unit || 0);
      categoryMap.set(item.category, entry);
    });
    addTable(
      doc,
      cursor,
      [['Category', 'Number of Items', 'Total Quantity', 'Total Inventory Value']],
      Array.from(categoryMap.entries())
        .sort((a, b) => b[1].value - a[1].value)
        .map(([category, entry]) => [
          category,
          String(entry.count),
          entry.qty.toLocaleString('en-IN'),
          formatCurrency(entry.value),
        ])
    );
  }

  // ---------- 3. Complete Inventory ----------
  addSectionTitle(doc, cursor, '3. Complete Inventory');
  if (items.length === 0) {
    addEmptyNotice(doc, cursor, 'No inventory items found.');
  } else {
    addTable(
      doc,
      cursor,
      [
        [
          'Item Name',
          'Category',
          'Qty',
          'Unit',
          'Price/Unit',
          'Total Value',
          'Purchase Date',
          'Expiry Date',
          'Storage Location',
          'Status',
        ],
      ],
      items.map((item) => [
        item.name,
        item.category,
        String(item.quantity ?? 0),
        item.unit,
        item.cost_per_unit != null ? formatCurrency(item.cost_per_unit) : 'N/A',
        formatCurrency((item.quantity || 0) * (item.cost_per_unit || 0)),
        formatDate(item.purchase_date),
        formatDate(item.expiry_date),
        item.storage_location || 'N/A',
        getItemStatus(item),
      ]),
      { 0: { cellWidth: 24 }, 8: { cellWidth: 22 } }
    );
  }

  // ---------- 4. Low Stock Report ----------
  addSectionTitle(doc, cursor, '4. Low Stock Report');
  const belowMinStockItems = items.filter(
    (i) => i.min_stock_level != null && (i.quantity ?? 0) < i.min_stock_level
  );
  if (belowMinStockItems.length === 0) {
    addEmptyNotice(doc, cursor, 'No Low Stock Items — all items are at or above their minimum stock level.');
  } else {
    addTable(
      doc,
      cursor,
      [['Item Name', 'Current Quantity', 'Minimum Stock Level', 'Suggested Restock Quantity']],
      belowMinStockItems.map((item) => [
        item.name,
        `${item.quantity ?? 0} ${item.unit}`,
        `${item.min_stock_level} ${item.unit}`,
        `${getSuggestedReorderQuantity(item)} ${item.unit}`,
      ])
    );
  }

  // ---------- 5. Expiry Report ----------
  addSectionTitle(doc, cursor, '5. Expiry Report');
  if (expiringSoonItems.length === 0) {
    addEmptyNotice(doc, cursor, 'No items expiring soon.');
  } else {
    const getRiskLevel = (item: InventoryItem): 'Low' | 'Medium' | 'High' => {
      const mlRisk = predictions?.predictions?.[item.id]?.expiry_risk;
      if (mlRisk) return mlRisk;
      const days = getDaysToExpiry(item.expiry_date);
      if (days === null) return 'Low';
      if (days < 2) return 'High';
      if (days <= 5) return 'Medium';
      return 'Low';
    };
    addTable(
      doc,
      cursor,
      [['Item Name', 'Expiry Date', 'Days Remaining', 'Risk Level']],
      expiringSoonItems
        .sort((a, b) => (getDaysToExpiry(a.expiry_date) ?? 0) - (getDaysToExpiry(b.expiry_date) ?? 0))
        .map((item) => [
          item.name,
          formatDate(item.expiry_date),
          formatExpiryLabel(item.expiry_date),
          getRiskLevel(item),
        ])
    );
  }

  // ---------- 6. ML Prediction Summary ----------
  addSectionTitle(doc, cursor, '6. ML Prediction Summary');
  ensureSpace(doc, cursor, 8);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.setTextColor(...(predictions?.is_ml ? GREEN_700 : GRAY_600));
  doc.text(
    `Prediction Source: ${predictions?.is_ml ? 'Live ML Model' : 'Heuristic Fallback'}`,
    MARGIN,
    cursor.y
  );
  cursor.y += 6;
  if (predictions?.model_metadata) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...GRAY_600);
    doc.text(
      `Model Confidence: ${predictions.model_metadata.model_confidence ?? 'N/A'}%   |   Next Peak Demand: ${formatDate(
        predictions.model_metadata.next_peak_demand_date
      )}`,
      MARGIN,
      cursor.y
    );
    cursor.y += 8;
  }

  const predictionEntries = predictions?.predictions
    ? items
        .filter((i) => predictions.predictions[i.id])
        .map((i) => ({ item: i, pred: predictions.predictions[i.id] }))
        .sort((a, b) => (b.pred.low_stock_probability ?? 0) - (a.pred.low_stock_probability ?? 0))
        .slice(0, 15)
    : [];

  if (predictionEntries.length === 0) {
    addEmptyNotice(doc, cursor, 'No ML predictions available for current inventory.');
  } else {
    addTable(
      doc,
      cursor,
      [['Item Name', '7-Day Demand Forecast', 'Low Stock Probability', 'Expiry Risk', 'Refill Date']],
      predictionEntries.map(({ item, pred }) => [
        item.name,
        Array.isArray(pred.demand_forecast)
          ? pred.demand_forecast.reduce((s, v) => s + v, 0).toFixed(1)
          : 'N/A',
        `${Math.round((pred.low_stock_probability ?? 0) * 100)}%`,
        pred.expiry_risk ?? 'N/A',
        pred.refill_date && pred.refill_date !== 'N/A' ? formatDate(pred.refill_date) : 'Immediate',
      ])
    );
  }

  // Purchase recommendations (mirrors PurchaseRecommendations.tsx logic)
  ensureSpace(doc, cursor, 8);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(...GRAY_800);
  doc.text('Purchase Recommendations', MARGIN, cursor.y);
  cursor.y += 6;

  const purchaseRecs = items
    .map((it) => {
      const score = getDaysLeft(it);
      const mlRefillDate = predictions?.predictions?.[it.id]?.refill_date;
      return { item: it, score, mlRefillDate };
    })
    .filter((r) => r.score <= 14)
    .sort((a, b) => a.score - b.score)
    .slice(0, 6);

  if (purchaseRecs.length === 0) {
    addEmptyNotice(doc, cursor, 'No immediate purchase recommendations.');
  } else {
    addTable(
      doc,
      cursor,
      [['Item Name', 'Predicted Refill Date']],
      purchaseRecs.map(({ item, mlRefillDate }) => [
        item.name,
        mlRefillDate && mlRefillDate !== 'N/A' ? formatDate(mlRefillDate) : 'Immediate',
      ])
    );
  }

  // ---------- 7. Spending & Cost Analysis ----------
  addSectionTitle(doc, cursor, '7. Spending & Cost Analysis');
  const expiredValue = items
    .filter((i) => isExpired(i.expiry_date))
    .reduce((sum, i) => sum + (i.quantity || 0) * (i.cost_per_unit || 0), 0);
  const monthlyConsumptionCost = items.reduce(
    (sum, i) => sum + (i.daily_usage || 0) * (i.cost_per_unit || 0) * 30,
    0
  );
  addTable(
    doc,
    cursor,
    [['Metric', 'Value']],
    [
      ['Total Inventory Value', formatCurrency(totalValue)],
      ['Estimated Value of Expired Items', formatCurrency(expiredValue)],
      ['Estimated Monthly Consumption Cost', formatCurrency(monthlyConsumptionCost)],
      ['Items Without Recorded Cost', String(items.length - itemsWithCost.length)],
    ],
    { 0: { cellWidth: 80 } }
  );

  ensureSpace(doc, cursor, 8);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10.5);
  doc.setTextColor(...GRAY_800);
  doc.text('Category-wise Spending', MARGIN, cursor.y);
  cursor.y += 6;
  const spendingByCategory = new Map<string, number>();
  items.forEach((item) => {
    spendingByCategory.set(
      item.category,
      (spendingByCategory.get(item.category) || 0) + (item.quantity || 0) * (item.cost_per_unit || 0)
    );
  });
  if (spendingByCategory.size === 0) {
    addEmptyNotice(doc, cursor, 'No category spending to display.');
  } else {
    addTable(
      doc,
      cursor,
      [['Category', 'Spending']],
      Array.from(spendingByCategory.entries())
        .sort((a, b) => b[1] - a[1])
        .map(([category, value]) => [category, formatCurrency(value)])
    );
  }

  // ---------- 8. Sustainability Report ----------
  addSectionTitle(doc, cursor, '8. Sustainability Report');
  const wastedItems = items.filter(isWasted);
  const totalWastedValue = wastedItems.reduce(
    (sum, i) => sum + (i.quantity || 0) * (i.cost_per_unit || 0),
    0
  );
  const totalWastedCO2 = wastedItems.reduce((sum, i) => sum + (i.quantity || 1) * getCO2Factor(i.category), 0);

  let totalUsed = 0;
  let totalWastedQty = 0;
  items
    .filter((i) => i.expiry_date)
    .forEach((item) => {
      const days = getDaysToExpiry(item.expiry_date);
      if (days === null) return;
      if (days < 0) {
        totalWastedQty += item.quantity || 0;
      } else {
        const expectedConsumption = (item.daily_usage || 0) * days;
        totalUsed += Math.min(item.quantity || 0, expectedConsumption);
        totalWastedQty += Math.max(0, (item.quantity || 0) - expectedConsumption);
      }
    });
  const usedBeforeExpiryPct =
    totalUsed + totalWastedQty > 0 ? (totalUsed / (totalUsed + totalWastedQty)) * 100 : null;

  const total = Math.max(1, items.length);
  const sustainabilityScore = Math.max(0, Math.round(((total - wastedItems.length) / total) * 100));

  addTable(
    doc,
    cursor,
    [['Metric', 'Value']],
    [
      ['Estimated Food Waste', `${wastedItems.length} item(s) — ${formatCurrency(totalWastedValue)}`],
      ['CO2 Impact', `${totalWastedCO2.toFixed(1)} kg CO2`],
      [
        'Used Before Expiry',
        usedBeforeExpiryPct !== null ? `${usedBeforeExpiryPct.toFixed(1)}%` : 'N/A (no perishable usage data)',
      ],
      ['Sustainability Score', `${sustainabilityScore} / 100`],
    ],
    { 0: { cellWidth: 80 } }
  );

  // ---------- 9. Consumption History ----------
  addSectionTitle(doc, cursor, '9. Consumption History');
  if (consumptionHistory.length === 0) {
    addEmptyNotice(doc, cursor, 'No consumption recorded yet.');
  } else {
    const totalConsumedEvents = consumptionHistory.length;
    const depletedCount = consumptionHistory.filter((entry) => entry.remainingQuantity === 0).length;
    ensureSpace(doc, cursor, 8);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(...GRAY_600);
    doc.text(
      `${totalConsumedEvents} consumption event(s) recorded — ${depletedCount} depleted stock to zero.`,
      MARGIN,
      cursor.y
    );
    cursor.y += 6;

    addTable(
      doc,
      cursor,
      [['Date', 'Item Name', 'Category', 'Quantity Consumed', 'Remaining Stock']],
      consumptionHistory.slice(0, 30).map((entry) => [
        new Date(entry.createdAt).toLocaleString(),
        entry.itemName,
        entry.category || 'N/A',
        `${entry.quantityConsumed} ${entry.unit}`,
        entry.remainingQuantity === 0 ? 'Out of Stock' : `${entry.remainingQuantity} ${entry.unit}`,
      ])
    );
  }

  addFootersToAllPages(doc);

  const dateStr = new Date().toISOString().slice(0, 10);
  doc.save(`HappyShelf_Inventory_Report_${dateStr}.pdf`);
};
